import {
  navBarHeight,
  minNavBarHeight,
  modulePageBackButton,
} from '../../themes/Sizes.js';

const sidebarStyles = {
  main_style: {
    transition: '.5s ease-in-out',
  },
  ul_style: {
    display: 'block',
    listStyleType: 'disc',
    marginBlockStart: '0em',
    marginBlockEnd: '0em',
    marginInlineStart: '0px',
    marginInlineEnd: '0px',
    paddingInlineStart: '0px',
  },
  nav_style: {
    fontFamily: 'Open Sans, sans-serif',
    fontSize: '18px',
    background: 'rgb(189,189,189)',
    bottom: '0',
    'box-shadow': '0 0 5px #666',
    height: '70%',
    'padding-top': '38px',
    'margin-top': `calc(max(${navBarHeight}vh,${minNavBarHeight}px) + ${modulePageBackButton}px)`,
    position: 'fixed',
    float: 'left',
    'overflow-y': 'auto',
    'overflow-x': 'hidden',
    direction: 'rtl',
    display: 'block',
    top: '0',
    left: '0',
    transition: '.5s ease-in-out',
    width: '17vw',
    minWidth: '250px',
  },
  nav_p: {
    color: '#000',
    display: 'block',
    padding: '12px 16px',
    transition: '.5s',
    'text-decoration': 'none',
    direction: 'ltr',
  },
  sidebar_item_link: {
    color: '#000',
    display: 'block',
    padding: '12px 24px',
    transition: '.5s',
    'text-decoration': 'none',
    'word-wrap': 'break-word',
    direction: 'ltr',
  },
  title_style: {
    fontSize: '24px',
    fontWeight: 700,
    wordWrap: 'break-word',
    marginBlockStart: '0em',
    marginBlockEnd: '0em',
    marginInlineStart: '0px',
    marginInlineEnd: '0px',
  },
  sub_title_style: {
    fontWeight: 700,
    padding: '12px 24px',
    marginBlockStart: '0em',
    marginBlockEnd: '0em',
    marginInlineStart: '0px',
    marginInlineEnd: '0px',
  },
  nav_back_style: {
    padding: '8px 0px',
    position: 'fixed',
    float: 'left',
    left: '2px',
    top: 0,
    fontSize: '20px',
    textAlign: 'center',
    color: '#000',
    backgroundColor: 'rgb(242,242,242)',
    fontWeight: '600',
    textDecoration: 'none',
    wordWrap: 'breakWord',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '17vw',
    minWidth: '250px',
    height: `${modulePageBackButton}px`,
    'margin-top': `calc(max(${navBarHeight}vh,${minNavBarHeight}px))`,
  },
  nav_expand_style: {
    transitionDelay: '.25s',
  },
};
export default sidebarStyles;
