name: Format CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16.13.0'

      - name: Install and format
        run: |
          npm install -g npm@8.1.3
          npm ci
          npm run format:check:ci
