# This is a basic workflow to help you get started with Actions

name: Test CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '16.13.0'

      # Setup JDK for java tests
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Install the apps using npm ci (ensures a clean install) and run the test target for ci (skips the NX cache ensuring a clean run)
      - name: Install and Test
        env:
          DB_NEO4J_URI: ${{ secrets.DB_NEO4J_URI }}
          DB_NEO4J_USERNAME: ${{ secrets.DB_NEO4J_USERNAME }}
          DB_NEO4J_PASSWORD: ${{ secrets.DB_NEO4J_PASSWORD }}
          MAIL_SENDER_PASSWORD: ${{ secrets.MAIL_SENDER_PASSWORD }}
        run: |
          npm install -g npm@8.1.3
          npm ci
          npm run test:ci
